---
name: Build repo packages

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true

      - name: Run build script
        run: bundle exec rake vox:build

      - name: openvox8-release
        uses: actions/upload-artifact@v4
        with:
          name: openvox8-release
          path: openvox8-release/output/
          retention-days: 7
          overwrite: true
          if-no-files-found: error

      - name: openvox7-release
        uses: actions/upload-artifact@v4
        with:
          name: openvox7-release
          path: openvox7-release/output/
          retention-days: 7
          overwrite: true
          if-no-files-found: error
